#!/bin/bash

sleep 18h

./resources/arcPostProcess.sh /media/julian/extHD/ 0 0
./resources/arcPostProcess.sh /media/julian/extHD/ 0 1
./resources/arcPostProcess.sh /media/julian/extHD/ 0 2
./resources/arcPostProcess.sh /media/julian/extHD/ 0 3
./resources/arcPostProcess.sh /media/julian/extHD/ 0 4
./resources/arcPostProcess.sh /media/julian/extHD/ 1 0
./resources/arcPostProcess.sh /media/julian/extHD/ 1 1
./resources/arcPostProcess.sh /media/julian/extHD/ 1 2
./resources/arcPostProcess.sh /media/julian/extHD/ 1 3
./resources/arcPostProcess.sh /media/julian/extHD/ 1 4
./resources/arcPostProcess.sh /media/julian/extHD/ 2 0
./resources/arcPostProcess.sh /media/julian/extHD/ 2 1
./resources/arcPostProcess.sh /media/julian/extHD/ 2 2
./resources/arcPostProcess.sh /media/julian/extHD/ 2 3
./resources/arcPostProcess.sh /media/julian/extHD/ 2 4
./resources/arcPostProcess.sh /media/julian/extHD/ 3 0
./resources/arcPostProcess.sh /media/julian/extHD/ 3 1
./resources/arcPostProcess.sh /media/julian/extHD/ 3 2
./resources/arcPostProcess.sh /media/julian/extHD/ 3 3
./resources/arcPostProcess.sh /media/julian/extHD/ 3 4
./resources/arcPostProcess.sh /media/julian/extHD/ 4 0
./resources/arcPostProcess.sh /media/julian/extHD/ 4 1
./resources/arcPostProcess.sh /media/julian/extHD/ 4 2
./resources/arcPostProcess.sh /media/julian/extHD/ 4 3
./resources/arcPostProcess.sh /media/julian/extHD/ 4 4
./resources/arcPostProcess.sh /media/julian/extHD/ 5 0
./resources/arcPostProcess.sh /media/julian/extHD/ 5 1
./resources/arcPostProcess.sh /media/julian/extHD/ 5 2
./resources/arcPostProcess.sh /media/julian/extHD/ 5 3
./resources/arcPostProcess.sh /media/julian/extHD/ 5 4
./resources/arcPostProcess.sh /media/julian/extHD/ 6 0
./resources/arcPostProcess.sh /media/julian/extHD/ 6 1
./resources/arcPostProcess.sh /media/julian/extHD/ 6 2
./resources/arcPostProcess.sh /media/julian/extHD/ 6 3
./resources/arcPostProcess.sh /media/julian/extHD/ 6 4
./resources/arcPostProcess.sh /media/julian/extHD/ 7 0
./resources/arcPostProcess.sh /media/julian/extHD/ 7 1
./resources/arcPostProcess.sh /media/julian/extHD/ 7 2
./resources/arcPostProcess.sh /media/julian/extHD/ 7 3
./resources/arcPostProcess.sh /media/julian/extHD/ 7 4
./resources/arcPostProcess.sh /media/julian/extHD/ 8 0
./resources/arcPostProcess.sh /media/julian/extHD/ 8 1
./resources/arcPostProcess.sh /media/julian/extHD/ 8 2
./resources/arcPostProcess.sh /media/julian/extHD/ 8 3
./resources/arcPostProcess.sh /media/julian/extHD/ 8 4
./resources/arcPostProcess.sh /media/julian/extHD/ 9 0
./resources/arcPostProcess.sh /media/julian/extHD/ 9 1
./resources/arcPostProcess.sh /media/julian/extHD/ 9 2
./resources/arcPostProcess.sh /media/julian/extHD/ 9 3
./resources/arcPostProcess.sh /media/julian/extHD/ 9 4
./resources/arcPostProcess.sh /media/julian/extHD/ 10 0
./resources/arcPostProcess.sh /media/julian/extHD/ 10 1
./resources/arcPostProcess.sh /media/julian/extHD/ 10 2
./resources/arcPostProcess.sh /media/julian/extHD/ 10 3
./resources/arcPostProcess.sh /media/julian/extHD/ 10 4
./resources/arcPostProcess.sh /media/julian/extHD/ 11 0
./resources/arcPostProcess.sh /media/julian/extHD/ 11 1
./resources/arcPostProcess.sh /media/julian/extHD/ 11 2
./resources/arcPostProcess.sh /media/julian/extHD/ 11 3
./resources/arcPostProcess.sh /media/julian/extHD/ 11 4
./resources/arcPostProcess.sh /media/julian/extHD/ 12 0
./resources/arcPostProcess.sh /media/julian/extHD/ 12 1
./resources/arcPostProcess.sh /media/julian/extHD/ 12 2
./resources/arcPostProcess.sh /media/julian/extHD/ 12 3
./resources/arcPostProcess.sh /media/julian/extHD/ 12 4
./resources/arcPostProcess.sh /media/julian/extHD/ 13 0
./resources/arcPostProcess.sh /media/julian/extHD/ 13 1
./resources/arcPostProcess.sh /media/julian/extHD/ 13 2
./resources/arcPostProcess.sh /media/julian/extHD/ 13 3
./resources/arcPostProcess.sh /media/julian/extHD/ 13 4
./resources/arcPostProcess.sh /media/julian/extHD/ 14 0
./resources/arcPostProcess.sh /media/julian/extHD/ 14 1
./resources/arcPostProcess.sh /media/julian/extHD/ 14 2
./resources/arcPostProcess.sh /media/julian/extHD/ 14 3
./resources/arcPostProcess.sh /media/julian/extHD/ 14 4
./resources/arcPostProcess.sh /media/julian/extHD/ 15 0
./resources/arcPostProcess.sh /media/julian/extHD/ 15 1
./resources/arcPostProcess.sh /media/julian/extHD/ 15 2
./resources/arcPostProcess.sh /media/julian/extHD/ 15 3
./resources/arcPostProcess.sh /media/julian/extHD/ 15 4
./resources/arcPostProcess.sh /media/julian/extHD/ 16 0
./resources/arcPostProcess.sh /media/julian/extHD/ 16 1
./resources/arcPostProcess.sh /media/julian/extHD/ 16 2
./resources/arcPostProcess.sh /media/julian/extHD/ 16 3
./resources/arcPostProcess.sh /media/julian/extHD/ 16 4
./resources/arcPostProcess.sh /media/julian/extHD/ 17 0
./resources/arcPostProcess.sh /media/julian/extHD/ 17 1
./resources/arcPostProcess.sh /media/julian/extHD/ 17 2
./resources/arcPostProcess.sh /media/julian/extHD/ 17 3
./resources/arcPostProcess.sh /media/julian/extHD/ 17 4
./resources/arcPostProcess.sh /media/julian/extHD/ 18 0
./resources/arcPostProcess.sh /media/julian/extHD/ 18 1
./resources/arcPostProcess.sh /media/julian/extHD/ 18 2
./resources/arcPostProcess.sh /media/julian/extHD/ 18 3
./resources/arcPostProcess.sh /media/julian/extHD/ 18 4
./resources/arcPostProcess.sh /media/julian/extHD/ 19 0
./resources/arcPostProcess.sh /media/julian/extHD/ 19 1
./resources/arcPostProcess.sh /media/julian/extHD/ 19 2
./resources/arcPostProcess.sh /media/julian/extHD/ 19 3
./resources/arcPostProcess.sh /media/julian/extHD/ 19 4
./resources/arcPostProcess.sh /media/julian/extHD/ 20 0
./resources/arcPostProcess.sh /media/julian/extHD/ 20 1
./resources/arcPostProcess.sh /media/julian/extHD/ 20 2
./resources/arcPostProcess.sh /media/julian/extHD/ 20 3
./resources/arcPostProcess.sh /media/julian/extHD/ 20 4
